name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: ${{ vars.APP_URL }}
          NEXT_PUBLIC_EDGE_FUNCTION_BASE_URL: ${{ vars.EDGE_FUNCTION_BASE_URL }}
          NEXT_PUBLIC_APP_DEEP_LINK: ${{ vars.APP_DEEP_LINK }}
      - run: npx electron-builder --win nsis --publish onTag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: ${{ vars.APP_URL }}
          NEXT_PUBLIC_EDGE_FUNCTION_BASE_URL: ${{ vars.EDGE_FUNCTION_BASE_URL }}
          NEXT_PUBLIC_APP_DEEP_LINK: ${{ vars.APP_DEEP_LINK }}
      - run: npx electron-builder --mac dmg zip --publish onTag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
